# THỰC HÀNH LAB 01 - LÀM QUEN VỚI PYTORCH
**Sinh viên:** Nguyễn Trương Cao Sơn
**Trường:** Đại học Sài Gòn

### Bài 1. Tạo Tensor cơ bản
**Yêu cầu:** Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [1]:
import torch
a = torch.tensor(
    [[1, 2, 3], 
    [4, 5, 6]], 
    dtype=torch.int32
    )

print('Tensor a:\n', a)
print('Kích thước:', a.shape)
print('Số chiều:', a.ndim)
print('Kiểu dữ liệu:', a.dtype)

Tensor a:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


**Trả lời:**
- Kích thước: `(2, 3)`
- Số chiều: `2`
- Kiểu dữ liệu: `torch.int32`

### Bài 2. Tạo các Tensor thường dùng
**Yêu cầu:**
- Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
- Tạo thêm một Tensor 5x5 chứa toàn giá trị 10.

In [3]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

f = torch.full((5, 5), 10)
print('Tensor 5x5 toàn 10:\n', f)

tensor([[0.9844, 0.2035, 0.7023, 0.6920],
        [0.6656, 0.8871, 0.2722, 0.1908],
        [0.7654, 0.1156, 0.9600, 0.8118]])
tensor([[-0.7069, -0.6070,  0.3227, -2.1986],
        [-1.7727, -0.9186,  0.1243,  0.9807],
        [ 0.1606, -0.4656,  0.5010, -2.9611]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Tensor 5x5 toàn 10:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


**Trả lời:**
- `torch.rand()`: Sinh số ngẫu nhiên theo phân phối đều trong khoảng [0, 1).
- `torch.randn()`: Sinh số ngẫu nhiên theo phân phối chuẩn tắc (mean = 0, std = 1).

### Bài 3. Kiểm tra thông tin Tensor
**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4]).

In [4]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


**Trả lời:**
- `torch.Size([2, 3, 4])` nghĩa là tensor 3 chiều. Chiều 0 có 2 phần tử, chiều 1 có 3 phần tử, chiều 2 có 4 phần tử. (Tổng có 2x3x4 = 24 phần tử).