# THỰC HÀNH LAB 01 - LÀM QUEN VỚI PYTORCH
**Sinh viên:** Nguyễn Trương Cao Sơn
**Trường:** Đại học Sài Gòn

### Bài 1. Tạo Tensor cơ bản
**Yêu cầu:** Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [1]:
import torch
a = torch.tensor(
    [[1, 2, 3], 
    [4, 5, 6]], 
    dtype=torch.int32
    )

print('Tensor a:\n', a)
print('Kích thước:', a.shape)
print('Số chiều:', a.ndim)
print('Kiểu dữ liệu:', a.dtype)

Tensor a:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


**Trả lời:**
- Kích thước: `(2, 3)`
- Số chiều: `2`
- Kiểu dữ liệu: `torch.int32`

### Bài 2. Tạo các Tensor thường dùng
**Yêu cầu:**
- Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
- Tạo thêm một Tensor 5x5 chứa toàn giá trị 10.

In [3]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

f = torch.full((5, 5), 10)
print('Tensor 5x5 toàn 10:\n', f)

tensor([[0.9844, 0.2035, 0.7023, 0.6920],
        [0.6656, 0.8871, 0.2722, 0.1908],
        [0.7654, 0.1156, 0.9600, 0.8118]])
tensor([[-0.7069, -0.6070,  0.3227, -2.1986],
        [-1.7727, -0.9186,  0.1243,  0.9807],
        [ 0.1606, -0.4656,  0.5010, -2.9611]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Tensor 5x5 toàn 10:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


**Trả lời:**
- `torch.rand()`: Sinh số ngẫu nhiên theo phân phối đều trong khoảng [0, 1).
- `torch.randn()`: Sinh số ngẫu nhiên theo phân phối chuẩn tắc (mean = 0, std = 1).

### Bài 3. Kiểm tra thông tin Tensor
**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4]).

In [4]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


**Trả lời:**
- `torch.Size([2, 3, 4])` nghĩa là tensor 3 chiều. Chiều 0 có 2 phần tử, chiều 1 có 3 phần tử, chiều 2 có 4 phần tử. (Tổng có 2x3x4 = 24 phần tử).

### Bài 4. Slicing và Indexing
**Yêu cầu:**
- Cho biết shape của a[1] và a[1:, 2:4].
- Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [6]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

phan_tu_cuoi = a[:, :, -2:]
print("\nHai phần tử cuối cùng trên chiều thứ ba:\n", phan_tu_cuoi)
print("Shape của hai phần tử cuối:", phan_tu_cuoi.shape)

Original tensor:
tensor([[[-0.1011, -0.5730,  0.4330,  0.6479,  0.7273],
         [-0.5315,  0.5131, -1.0418,  0.5628,  0.5342],
         [-1.7856,  0.0052,  0.3024,  0.3201, -2.8984],
         [-0.0343,  1.9460,  0.2864,  1.2175, -0.9606]],

        [[ 1.3040,  0.8783, -0.6282, -1.3843, -0.1482],
         [ 0.9053, -1.1175,  0.6982, -0.4348,  1.0785],
         [ 0.4107,  0.7262,  1.4194,  1.0854, -0.1706],
         [ 0.2742,  2.1336,  0.2313, -0.9929, -0.5094]],

        [[-0.1589, -0.6907,  1.5446,  1.1176, -0.3674],
         [-0.4789, -1.1221,  0.7844,  0.7632, -0.0666],
         [-0.5603, -1.1454, -0.3305,  0.1982,  1.1709],
         [-0.5758, -0.7606,  1.3626,  0.4511,  0.8997]]])

Tensor a[1]:
tensor([[ 1.3040,  0.8783, -0.6282, -1.3843, -0.1482],
        [ 0.9053, -1.1175,  0.6982, -0.4348,  1.0785],
        [ 0.4107,  0.7262,  1.4194,  1.0854, -0.1706],
        [ 0.2742,  2.1336,  0.2313, -0.9929, -0.5094]])

Tensor a[1:, 2:4]:
tensor([[[ 0.4107,  0.7262,  1.4194,  1.0854, -0.1

**Trả lời:**
- Shape của `a[1]` là `torch.Size([4, 5])`.
- Shape của `a[1:, 2:4]` là `torch.Size([2, 2, 5])`.
- Code lấy 2 phần tử cuối: `a[:, :, -2:]`.

### Bài 5. Reshape và Flatten
**Yêu cầu:**
- Kiểm tra số phần tử trước và sau khi reshape.
- Thử reshape Tensor thành kích thước 2x6.

In [ ]:
import torch
a = torch.randn(3, 4)

print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

print("\nSố phần tử trước khi reshape:", a.numel())
print("Số phần tử sau khi reshape:", a.reshape(3, 2, 2).numel())

print("\nReshape thành kích thước 2x6:\n", a.reshape(2, 6))

Original:
tensor([[-0.8865, -1.1929, -0.0925, -1.0800],
        [-0.1380, -0.2881, -0.3158,  0.1086],
        [ 1.2573, -0.0222,  0.4832, -0.3377]])

Flatten:
tensor([-0.8865, -1.1929, -0.0925, -1.0800, -0.1380, -0.2881, -0.3158,  0.1086,
         1.2573, -0.0222,  0.4832, -0.3377])

Reshape to 3 x 2 x 2:
tensor([[[-0.8865, -1.1929],
         [-0.0925, -1.0800]],

        [[-0.1380, -0.2881],
         [-0.3158,  0.1086]],

        [[ 1.2573, -0.0222],
         [ 0.4832, -0.3377]]])

Số phần tử trước khi reshape: 12
Số phần tử sau khi reshape: 12

Reshape thành kích thước 2x6:
 tensor([[-0.8865, -1.1929, -0.0925, -1.0800, -0.1380, -0.2881],
        [-0.3158,  0.1086,  1.2573, -0.0222,  0.4832, -0.3377]])


**Trả lời Bài 5:**
- Số phần tử trước và sau khi reshape không thay đổi (đều bằng 12 phần tử).